spring:
  datasource:
    #    url: jdbc:h2:./database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    #    driver-class-name: org.h2.Driver
    datasource:
    url: jdbc:postgresql://localhost:5433/instagram-axon
    username: super_admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8090